[tool.poetry]
name = "how-do-i"
version = "0.1.0"
description = "A collection of solutions that solve common problems."
authors = ["Jerod Gawne <Jerod.Gawne@intusurg.com>"]

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]
black = {extras = ["d"], version = "^22.6.0"}
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-runner = "^6.0.0"
Faker = "^14.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
