# Ubuntu 22.10 Base Docker Image Optimized for Containers (Development)

# Copyright ©2020-2022 Jerod Gawne <https://github.com/jerodg>

#This program is free software: you can redistribute it and/or modify
#it under the terms of the Server Side Public License (SSPL) as
#published by MongoDB, Inc., either version 1 of the
#License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#SSPL for more details.

#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#You should have received a copy of the SSPL along with this program.
#If not, see <https://www.mongodb.com/licensing/server-side-public-license>.

FROM ubuntu:kinetic


# Prequisites
RUN apt-get update
RUN apt full-upgrade
RUN apt autoclean
RUN apt autoremove
#RUN apt-get -y install tzdata
#RUN echo "UTC" > /etc/timezone
#RUN rm -f /etc/localtime
#RUN dpkg-reconfigure -f noninteractive tzdata


# Python
RUN apt-get -y install \
               wget \
               build-essential \
               gdb \
               lcov \
               pkg-config \
               libbz2-dev \
               libffi-dev \
               libgdbm-dev \
               libgdbm-compat-dev \
               liblzma-dev \
               libncurses5-dev \
               libreadline6-dev \
               libsqlite3-dev \
               libssl-dev \
               lzma \
               lzma-dev \
               tk-dev \
               uuid-dev \
               zlib1g-dev \
               libldap2-dev \
               python3-dev \
               libsasl2-dev \
               libc6-dev

# # Get Source
WORKDIR /tmp
RUN wget https://www.python.org/ftp/python/3.10.6/Python-3.10.6.tgz
RUN tar xf Python-3.10.6.tgz

# Build Source
WORKDIR /tmp/Python-3.10.6
RUN ./configure --enable-optimizations \
                --enable-loadable-sqlite-extensions \
                --enable-big-digits=30 \
                --with-ensurepip=upgrade \
                --with-lto \
                --with-computed-gotos

RUN make -j$(($(nproc) / 2) - 1)
RUN make -j$(($(nproc) / 2) - 1) install

# Configure Shared Link Library
#RUN strip /usr/local/lib/libpython3.8.so.1.0
#RUN ldconfig

# Configure Symbolic Links
#WORKDIR /usr/local/bin
#RUN ln -s /usr/local/bin/python3.8 python
#RUN ln -s /usr/local/bin/pip3.8 pip

# Update Core Python Packages
#RUN pip install --upgrade pip setuptools

# Cleanup
RUN rm -rf /tmp/*
RUN python3 -m pip install --upgrade pip setuptools wheel certifi
RUN curl -sSL https://install.python-poetry.org | python3 -

#RUN apt-get autoclean
#RUN apt-get autoremove

RUN mkdir /opt/hdi
WORKDIR /opt/hdi
COPY src/*.* /opt/hdi
COPY ./pyproject.toml /opt/hdi
RUN poetry install

#LABEL org.opencontainers.image.vendor="Mhi Inc."
#LABEL org.opencontainers.image.url=https://jerodg.dev
#LABEL org.opencontainers.image.title="Ubuntu 20.04 w/Python 3.8.2"
#LABEL org.opencontainers.image.description="Ubuntu 20.04 Base Docker Image Optimized for Containers w/Python 3.8.2"
#LABEL org.opencontainers.image.version=1.1.0
#LABEL org.opencontainers.image.documentation=https://github.com/jerodg

# Use For Development; Keeps the Container Running
# ENTRYPOINT ["/bin/bash", "-c", "while true; do sleep 1; done"]
